### PR TITLE
Check for ActionDispatch instead of Rails logger

### PR DESCRIPTION
**Pull request by entretechno-jeremiah**
[The usage instructions specify to create an initializer for using the middleware](https://github.com/stve/silencer/tree/v1.1.0#rails), which usually happens before [`Rails.logger` is set](https://github.com/stve/silencer/pull/29). So in most Rails applications, it mistakenly uses `Silencer::Rack::Logger`:

```
Puma caught this error: invalid log level:  (ArgumentError)
/home/jm/.rbenv/versions/3.1.1/lib/ruby/3.1.0/logger.rb:268:in `level='
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/logger.rb:14:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/silencer-1.1.0/lib/silencer/rack/logger.rb:31:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/server_timing.rb:20:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/static.rb:23:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-mini-profiler-3.0.0/lib/mini_profiler/profiler.rb:393:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/engine.rb:530:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/configuration.rb:252:in `call'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/request.rb:77:in `block in handle_request'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/request.rb:76:in `handle_request'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/server.rb:441:in `process_client'
/home/jm/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

This change checks if `ActionDispatch` has been loaded instead, which should still fix the issue reported in #29 (@smridge I'd love your feedback on this change if you're available :heart:).

### CODE REVIEW

**Comment by stve** [comment]
Thanks for reporting this! This was a newly added change in the latest version, you could probably revert to an older version for the time being until this is merged/released. Tests broke but I don't think it is related your change. I'll look into it.

**Comment by entretechno-jeremiah** [comment]
> Tests broke but I don't think it is related your change.

Just submitted #34 to fix this!

**Comment by smridge** [comment]
> @smridge I'd love your feedback on this change if you're available

This actually breaks the fix from https://github.com/stve/silencer/pull/29 😞 The `Rails.logger.present?`...or really`Rails.logger` needs to be added back for applications that use `activerecord` as a standalone gem but not Rails itself.

This is the output from using a `racksh` session (comparable to a `rails c`) for an application that uses `activerecord` only:
```ruby
> defined?(Rails)
=> "constant"
> Rails.logger.present?
=> false
> Rails.logger
=> nil
> defined?(ActionDispatch)
=> "constant"
```

**Comment by smridge** [comment]
hmmm given we only care if the `Rails.logger` is present. I'd propose really slimming that line of code down to `Rails&.logger` (don't even worry about what is defined) the safe navigation will take care of that.

**Comment by tindron** [comment]
We don't care if `Rails.logger` is present because it can be nil when used with or without rails.  Adding a check for it breaks the rails use case.

**Comment by entretechno-jeremiah** [comment]
@smridge Darn. I don't suppose `action_dispatch` is being required somewhere in your code maybe?

```ruby
require 'active_record'
defined?(ActionDispatch)
#=> nil
require 'action_dispatch'
defined?(ActionDispatch)
#=> "constant"
```

@stve What are your thoughts on letting users use `Silencer::Rails::Logger`/`Silencer::Rack::Logger` directly without having to rely on [the environment detection](https://github.com/stve/silencer/blob/v1.1.0/lib/silencer/logger.rb#L7-L12) to use it as `Silencer::Logger`? (@smridge It looks like you can already do this with `Silencer::Rack::Logger`; maybe that's a preferable solution?)

**Comment by smridge** [comment]
> @smridge Darn. I don't suppose `action_dispatch` is being required somewhere in your code maybe?
> 
> ```ruby
> require 'active_record'
> defined?(ActionDispatch)
> #=> nil
> require 'action_dispatch'
> defined?(ActionDispatch)
> #=> "constant"
> ```

Uff good catch. Always a fun journey looking at the dependency tree of things. Ok, so the particular app has the `active_model_serializers` gem, which has a transitive dependency of `actionpack` in which that is where [`ActionDispatch`](https://api.rubyonrails.org/classes/ActionDispatch.html) lives.


> @stve What are your thoughts on letting users use `Silencer::Rails::Logger`/`Silencer::Rack::Logger` directly without having to rely on [the environment detection](https://github.com/stve/silencer/blob/v1.1.0/lib/silencer/logger.rb#L7-L12) to use it as `Silencer::Logger`? (@smridge It looks like you can already do this with `Silencer::Rack::Logger`; maybe that's a preferable solution?)

Also good catch. I'm 👍 for a configurable approach. I think the `rails?` check would still be good to keep to ensure users configure correctly.

**Comment by stve** [comment]
@entretechno-jeremiah it's funny you should mention that because I was thinking along the same lines. Rails detection is used to simplify the require logic to just `require "silencer/logger"`

But this could be more explicit when requiring the gem vs trying to detect when an app is using Rails or Rack. Then you can decide which is more applicable for your use case. Something like:

```ruby
# rails apps
require "silencer/rails/logger"

# rack apps
require "silencer/rack/logger"
```

I think this could be supported rather easily, but probably also needs a major version bump since this could change the API.

**Comment by smridge** [comment]
I think that ☝️ is a great approach and makes the configuration much more clear. Yes, agree, it is definitely a `BREAKING CHANGE`.

**Pull request merged**
